/*
 Enter your query here.
 */
SELECT
   HACKERS.HACKER_ID,
   NAME,
   SUM(SCORE) AS TOTAL_SCORE
FROM
   HACKERS
   INNER JOIN (
      SELECT
         HACKER_ID,
         MAX(SCORE) AS SCORE
      FROM
         SUBMISSIONS
      GROUP BY
         HACKER_ID,
         CHALLENGE_ID
   ) AS MAX_SCORE_STATS ON HACKERS.HACKER_ID = MAX_SCORE_STATS.HACKER_ID
GROUP BY
   HACKERS.HACKER_ID,
   NAME
HAVING
   TOTAL_SCORE > 0
ORDER BY
   TOTAL_SCORE DESC,
   HACKERS.HACKER_ID