/*
 Enter your query here.
 */
SELECT SUBMISSION_DATE,
       (
           SELECT COUNT(DISTINCT HACKER_ID)
           FROM SUBMISSIONS AS SUBMISSIONS1
           WHERE SUBMISSION_DATE_STATS.SUBMISSION_DATE = SUBMISSIONS1.SUBMISSION_DATE
             AND (
                     SELECT COUNT(DISTINCT SUBMISSIONS2.SUBMISSION_DATE)
                     FROM SUBMISSIONS AS SUBMISSIONS2
                     WHERE SUBMISSIONS1.HACKER_ID = SUBMISSIONS2.HACKER_ID
                       AND SUBMISSION_DATE_STATS.SUBMISSION_DATE > SUBMISSIONS2.SUBMISSION_DATE
                 ) = DATEDIFF(
                         SUBMISSION_DATE_STATS.SUBMISSION_DATE,
                         '2016-03-01'
                     )
       ),
       (
           SELECT HACKER_ID
           FROM SUBMISSIONS
           WHERE SUBMISSION_DATE_STATS.SUBMISSION_DATE = SUBMISSIONS.SUBMISSION_DATE
           GROUP BY HACKER_ID
           ORDER BY COUNT(SUBMISSION_ID) DESC,
                    HACKER_ID
           LIMIT
    1 ) AS THE_HACKER_MADE_MAXIMUM_NUMBER_OF_SUBMISSIONS,
   (
      SELECT
         NAME
      FROM
         HACKERS
      WHERE
         HACKER_ID = THE_HACKER_MADE_MAXIMUM_NUMBER_OF_SUBMISSIONS
   )
FROM
    (
    SELECT
    DISTINCT SUBMISSION_DATE
    FROM
    SUBMISSIONS
    ) AS SUBMISSION_DATE_STATS
GROUP BY
    SUBMISSION_DATE