/*
 Enter your query here.
 */
SELECT
   NAME
FROM
   STUDENTS
   INNER JOIN FRIENDS ON STUDENTS.ID = FRIENDS.ID
   INNER JOIN PACKAGES AS PACKAGES1 ON STUDENTS.ID = PACKAGES1.ID
   INNER JOIN PACKAGES AS PACKAGES2 ON FRIENDS.FRIEND_ID = PACKAGES2.ID
WHERE
   PACKAGES1.SALARY < PACKAGES2.SALARY
ORDER BY
   PACKAGES2.SALARY