/*
 Enter your query here.
 */
SELECT
   FUNCTIONS1.X,
   FUNCTIONS1.Y
FROM
   FUNCTIONS AS FUNCTIONS1
   INNER JOIN FUNCTIONS AS FUNCTIONS2 ON FUNCTIONS1.X = FUNCTIONS2.Y
   AND FUNCTIONS1.Y = FUNCTIONS2.X
GROUP BY
   FUNCTIONS1.X,
   FUNCTIONS1.Y
HAVING
   COUNT(FUNCTIONS1.X) > 1
   OR FUNCTIONS1.X < FUNCTIONS1.Y
ORDER BY
   FUNCTIONS1.X